// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backup.proto

package backup_rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	DataType             string   `protobuf:"bytes,1,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetDataType() string {
	if m != nil {
		return m.DataType
	}
	return ""
}

func (m *Data) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Error struct {
	Info                 string   `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

type SaveRequest struct {
	Data                 *Data    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	TaskName             string   `protobuf:"bytes,2,opt,name=task_name,json=taskName,proto3" json:"task_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SaveRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

type SaveResponse struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{3}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type CloseRequest struct {
	TaskName             string   `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	TypeName             string   `protobuf:"bytes,2,opt,name=TypeName,proto3" json:"TypeName,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseRequest) Reset()         { *m = CloseRequest{} }
func (m *CloseRequest) String() string { return proto.CompactTextString(m) }
func (*CloseRequest) ProtoMessage()    {}
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{4}
}

func (m *CloseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseRequest.Unmarshal(m, b)
}
func (m *CloseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseRequest.Marshal(b, m, deterministic)
}
func (m *CloseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseRequest.Merge(m, src)
}
func (m *CloseRequest) XXX_Size() int {
	return xxx_messageInfo_CloseRequest.Size(m)
}
func (m *CloseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseRequest proto.InternalMessageInfo

func (m *CloseRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *CloseRequest) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *CloseRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type CloseResponse struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseResponse) Reset()         { *m = CloseResponse{} }
func (m *CloseResponse) String() string { return proto.CompactTextString(m) }
func (*CloseResponse) ProtoMessage()    {}
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{5}
}

func (m *CloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseResponse.Unmarshal(m, b)
}
func (m *CloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseResponse.Marshal(b, m, deterministic)
}
func (m *CloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseResponse.Merge(m, src)
}
func (m *CloseResponse) XXX_Size() int {
	return xxx_messageInfo_CloseResponse.Size(m)
}
func (m *CloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseResponse proto.InternalMessageInfo

func (m *CloseResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

type DestroyRequest struct {
	TaskName             string   `protobuf:"bytes,1,opt,name=TaskName,proto3" json:"TaskName,omitempty"`
	TypeName             string   `protobuf:"bytes,2,opt,name=TypeName,proto3" json:"TypeName,omitempty"`
	Time                 int64    `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyRequest) Reset()         { *m = DestroyRequest{} }
func (m *DestroyRequest) String() string { return proto.CompactTextString(m) }
func (*DestroyRequest) ProtoMessage()    {}
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{6}
}

func (m *DestroyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyRequest.Unmarshal(m, b)
}
func (m *DestroyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyRequest.Marshal(b, m, deterministic)
}
func (m *DestroyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyRequest.Merge(m, src)
}
func (m *DestroyRequest) XXX_Size() int {
	return xxx_messageInfo_DestroyRequest.Size(m)
}
func (m *DestroyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyRequest proto.InternalMessageInfo

func (m *DestroyRequest) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *DestroyRequest) GetTypeName() string {
	if m != nil {
		return m.TypeName
	}
	return ""
}

func (m *DestroyRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type DestroyResponse struct {
	Err                  *Error   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DestroyResponse) Reset()         { *m = DestroyResponse{} }
func (m *DestroyResponse) String() string { return proto.CompactTextString(m) }
func (*DestroyResponse) ProtoMessage()    {}
func (*DestroyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{7}
}

func (m *DestroyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DestroyResponse.Unmarshal(m, b)
}
func (m *DestroyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DestroyResponse.Marshal(b, m, deterministic)
}
func (m *DestroyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DestroyResponse.Merge(m, src)
}
func (m *DestroyResponse) XXX_Size() int {
	return xxx_messageInfo_DestroyResponse.Size(m)
}
func (m *DestroyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DestroyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DestroyResponse proto.InternalMessageInfo

func (m *DestroyResponse) GetErr() *Error {
	if m != nil {
		return m.Err
	}
	return nil
}

func init() {
	proto.RegisterType((*Data)(nil), "backup_rpc.Data")
	proto.RegisterType((*Error)(nil), "backup_rpc.Error")
	proto.RegisterType((*SaveRequest)(nil), "backup_rpc.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "backup_rpc.SaveResponse")
	proto.RegisterType((*CloseRequest)(nil), "backup_rpc.CloseRequest")
	proto.RegisterType((*CloseResponse)(nil), "backup_rpc.CloseResponse")
	proto.RegisterType((*DestroyRequest)(nil), "backup_rpc.DestroyRequest")
	proto.RegisterType((*DestroyResponse)(nil), "backup_rpc.DestroyResponse")
}

func init() { proto.RegisterFile("backup.proto", fileDescriptor_65240d19de191688) }

var fileDescriptor_65240d19de191688 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x53, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0x7e, 0x7d, 0xe5, 0xbd, 0xd7, 0x0e, 0xe5, 0xa9, 0x7b, 0xb1, 0x96, 0x0b, 0x59, 0x3d, 0xf4,
	0xc4, 0x01, 0x8c, 0x77, 0x11, 0x4f, 0x26, 0xc4, 0x14, 0x4e, 0xc6, 0x84, 0x2c, 0x38, 0x26, 0x04,
	0x61, 0xd7, 0xed, 0x42, 0xd2, 0xff, 0xea, 0x8f, 0x31, 0xb3, 0xdd, 0x62, 0x89, 0x5c, 0x38, 0x78,
	0x9b, 0x99, 0x6f, 0xf7, 0x9b, 0x6f, 0xbe, 0x9d, 0x85, 0x68, 0x26, 0xe6, 0xcb, 0x8d, 0xea, 0x2a,
	0x2d, 0x8d, 0x64, 0x50, 0x66, 0x53, 0xad, 0xe6, 0xfc, 0x01, 0x1a, 0x43, 0x61, 0x04, 0x6b, 0x43,
	0xf8, 0x22, 0x8c, 0x98, 0x9a, 0x42, 0x61, 0xec, 0x75, 0xbc, 0x34, 0xcc, 0x02, 0x2a, 0x4c, 0x0a,
	0x85, 0x8c, 0x41, 0xc3, 0x2c, 0x56, 0x18, 0xff, 0xee, 0x78, 0xa9, 0x9f, 0xd9, 0x98, 0x6a, 0x84,
	0xc7, 0x7e, 0xc7, 0x4b, 0xa3, 0xcc, 0xc6, 0xbc, 0x0d, 0x7f, 0xee, 0xb5, 0x96, 0x9a, 0xc0, 0xc5,
	0xfa, 0x55, 0x3a, 0x22, 0x1b, 0xf3, 0x47, 0x68, 0x8e, 0xc5, 0x16, 0x33, 0x7c, 0xdf, 0x60, 0x6e,
	0xd8, 0x95, 0xbb, 0x4f, 0x47, 0x9a, 0xbd, 0xd3, 0xee, 0x97, 0xa6, 0x2e, 0x09, 0x2a, 0x19, 0x49,
	0x96, 0x11, 0xf9, 0x72, 0xba, 0x16, 0xae, 0x7d, 0x98, 0x05, 0x54, 0x18, 0x89, 0x15, 0xf2, 0x3e,
	0x44, 0x25, 0x63, 0xae, 0xe4, 0x3a, 0x47, 0x76, 0x09, 0x3e, 0x6a, 0xed, 0x18, 0xcf, 0xea, 0x8c,
	0x56, 0x55, 0x46, 0x28, 0x7f, 0x82, 0xe8, 0xee, 0x4d, 0xe6, 0x3b, 0x1d, 0x09, 0x04, 0x13, 0x47,
	0x58, 0xcd, 0x5d, 0xe5, 0x16, 0x2b, 0x14, 0x8e, 0x6a, 0xcd, 0xab, 0x9c, 0x46, 0x9c, 0x90, 0x27,
	0x7e, 0xe9, 0x09, 0xc5, 0xfc, 0x1a, 0x5a, 0x8e, 0xfb, 0x18, 0x45, 0xcf, 0xf0, 0x7f, 0x88, 0xb9,
	0xd1, 0xb2, 0xf8, 0x09, 0x4d, 0x37, 0x70, 0xb2, 0x63, 0x3f, 0x42, 0x55, 0xef, 0xc3, 0x83, 0xd6,
	0xc0, 0x22, 0x63, 0xd4, 0xdb, 0xc5, 0x1c, 0xd9, 0x2d, 0x04, 0x64, 0xb7, 0x5d, 0x97, 0xf3, 0xfa,
	0xad, 0xda, 0xb3, 0x26, 0xf1, 0x77, 0xa0, 0xec, 0xca, 0x7f, 0xa5, 0x1e, 0x1b, 0x40, 0x68, 0x0d,
	0xb2, 0x5b, 0xb5, 0x77, 0xb4, 0xfe, 0x26, 0xc9, 0xc5, 0x01, 0xa4, 0x62, 0x61, 0x43, 0xf8, 0xe7,
	0x06, 0x62, 0xc9, 0xde, 0xd6, 0xec, 0x79, 0x98, 0xb4, 0x0f, 0x62, 0x15, 0xcb, 0xec, 0xaf, 0xfd,
	0x0a, 0xfd, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x7b, 0xe7, 0xe2, 0x1a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackupServiceClient interface {
	SaveData(ctx context.Context, opts ...grpc.CallOption) (BackupService_SaveDataClient, error)
	CloseType(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
	Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
}

type backupServiceClient struct {
	cc *grpc.ClientConn
}

func NewBackupServiceClient(cc *grpc.ClientConn) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) SaveData(ctx context.Context, opts ...grpc.CallOption) (BackupService_SaveDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BackupService_serviceDesc.Streams[0], "/backup_rpc.BackupService/SaveData", opts...)
	if err != nil {
		return nil, err
	}
	x := &backupServiceSaveDataClient{stream}
	return x, nil
}

type BackupService_SaveDataClient interface {
	Send(*SaveRequest) error
	CloseAndRecv() (*SaveResponse, error)
	grpc.ClientStream
}

type backupServiceSaveDataClient struct {
	grpc.ClientStream
}

func (x *backupServiceSaveDataClient) Send(m *SaveRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *backupServiceSaveDataClient) CloseAndRecv() (*SaveResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SaveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *backupServiceClient) CloseType(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, "/backup_rpc.BackupService/CloseType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) Destroy(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, "/backup_rpc.BackupService/Destroy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServiceServer is the server API for BackupService service.
type BackupServiceServer interface {
	SaveData(BackupService_SaveDataServer) error
	CloseType(context.Context, *CloseRequest) (*CloseResponse, error)
	Destroy(context.Context, *DestroyRequest) (*DestroyResponse, error)
}

// UnimplementedBackupServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBackupServiceServer struct {
}

func (*UnimplementedBackupServiceServer) SaveData(srv BackupService_SaveDataServer) error {
	return status.Errorf(codes.Unimplemented, "method SaveData not implemented")
}
func (*UnimplementedBackupServiceServer) CloseType(ctx context.Context, req *CloseRequest) (*CloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseType not implemented")
}
func (*UnimplementedBackupServiceServer) Destroy(ctx context.Context, req *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Destroy not implemented")
}

func RegisterBackupServiceServer(s *grpc.Server, srv BackupServiceServer) {
	s.RegisterService(&_BackupService_serviceDesc, srv)
}

func _BackupService_SaveData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BackupServiceServer).SaveData(&backupServiceSaveDataServer{stream})
}

type BackupService_SaveDataServer interface {
	SendAndClose(*SaveResponse) error
	Recv() (*SaveRequest, error)
	grpc.ServerStream
}

type backupServiceSaveDataServer struct {
	grpc.ServerStream
}

func (x *backupServiceSaveDataServer) SendAndClose(m *SaveResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *backupServiceSaveDataServer) Recv() (*SaveRequest, error) {
	m := new(SaveRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _BackupService_CloseType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).CloseType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup_rpc.BackupService/CloseType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).CloseType(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup_rpc.BackupService/Destroy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).Destroy(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backup_rpc.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CloseType",
			Handler:    _BackupService_CloseType_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _BackupService_Destroy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaveData",
			Handler:       _BackupService_SaveData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "backup.proto",
}
